import {
  Brain,
  CalendarCheck,
  FileText,
  LayoutDashboard,
  Map as MapIcon,
  Users,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { Role } from './types';

export const APP_NAME = 'RuralConnect';
export const INDIA_CENTER: [number, number] = [20.5937, 78.9629];
export const INDIA_ZOOM = 5;

export const RECORD_TYPES = [
  'Blood Test',
  'X-Ray',
  'MRI',
  'Prescription',
  'ECG',
  'Other',
] as const;

export const DISEASE_COLORS: Record<string, string> = {
  Dengue: '#ff4444',
  Malaria: '#ff8800',
  Tuberculosis: '#ffcc00',
  Typhoid: '#00ff88',
  Pneumonia: '#00ccff',
  'Hepatitis B': '#aa44ff',
  Diabetes: '#ff44aa',
  'Common Cold': '#44ffcc',
};

export const FALLBACK_DISEASE_COLORS = [
  '#ff6b6b',
  '#ffd166',
  '#06d6a0',
  '#4cc9f0',
  '#c77dff',
  '#f72585',
  '#90be6d',
  '#f9844a',
] as const;

export interface NavItem {
  label: string;
  to: string;
  icon: LucideIcon;
}

export const NAV_LINKS: Record<Role, NavItem[]> = {
  patient: [
    { label: 'Dashboard', to: '/patient/dashboard', icon: LayoutDashboard },
    { label: 'View previous cases', to: '/patient/history', icon: FileText },
    { label: 'Add new case', to: '/patient/predict', icon: Brain },
    { label: 'Medical Records', to: '/patient/records', icon: CalendarCheck },
  ],
  doctor: [
    { label: 'Dashboard', to: '/doctor/dashboard', icon: LayoutDashboard },
    { label: 'Patient Cases', to: '/doctor/patients', icon: Users },
    { label: 'Disease Heatmap', to: '/doctor/heatmap', icon: MapIcon },
  ],
};

export const SYMPTOM_CATEGORY_ORDER = [
  'Fever',
  'Respiratory',
  'Digestive',
  'Neurological',
  'Musculoskeletal',
  'Skin',
  'Liver',
  'Urinary',
  'Eyes/ENT',
  'General',
] as const;

export const SYMPTOM_CATEGORY_KEYS: Record<(typeof SYMPTOM_CATEGORY_ORDER)[number], string[]> = {
  Fever: ['highfever', 'mildfever', 'shivering', 'chills', 'sweating'],
  Respiratory: [
    'cough',
    'breathlessness',
    'chestpain',
    'phlegm',
    'mucoidsputum',
    'bloodinsputum',
    'continuoussneezing',
    'congestion',
    'rustysputum',
  ],
  Digestive: [
    'vomiting',
    'nausea',
    'diarrhoea',
    'constipation',
    'abdominalpain',
    'stomachpain',
    'bellypain',
    'indigestion',
    'acidity',
    'stomachbleeding',
    'bloodystool',
    'distentionofabdomen',
    'passageofgases',
    'swellingofstomach',
    'painduringbowelmovements',
    'paininanalregion',
    'irritationinanus',
  ],
  Neurological: [
    'headache',
    'dizziness',
    'lossofbalance',
    'alteredsensorium',
    'slurredspeech',
    'spinningmovements',
    'unsteadiness',
    'coma',
    'depression',
    'anxiety',
    'moodswings',
    'lackofconcentration',
    'lossofsmell',
    'blurredanddistortedvision',
    'visualdisturbances',
    'weaknessofonebodyside',
  ],
  Musculoskeletal: [
    'jointpain',
    'musclepain',
    'backpain',
    'neckpain',
    'kneepain',
    'hipjointpain',
    'muscleweakness',
    'musclewasting',
    'stiffneck',
    'movementstiffness',
    'painfulwalking',
    'swellingjoints',
    'weaknessinlimbs',
    'cramps',
  ],
  Skin: [
    'skinrash',
    'itching',
    'nodalskineruptions',
    'skinpeeling',
    'pusfilledpimples',
    'blackheads',
    'blister',
    'redspotsoverbody',
    'yellowcrustooze',
    'silverlikedusting',
    'dischromicpatches',
    'redsorearoundnose',
    'bruising',
    'scurring',
  ],
  Liver: [
    'yellowishskin',
    'yellowingofeyes',
    'darkurine',
    'yellowurine',
    'acuteliverfailure',
    'internalitching',
  ],
  Urinary: [
    'burningmicturition',
    'bladderdiscomfort',
    'continuousfeelofurine',
    'foulsmellofurine',
    'spottingurination',
  ],
  'Eyes/ENT': [
    'rednessofeyes',
    'wateringfromeyes',
    'throatirritation',
    'patchesinthroat',
    'enlargedthyroid',
    'sinuspressure',
    'runnynose',
  ],
  General: [
    'fatigue',
    'lethargy',
    'malaise',
    'dehydration',
    'lossofappetite',
    'weightloss',
    'weightgain',
    'obesity',
    'restlessness',
    'irritability',
    'fastheartrate',
    'palpitations',
    'fluidoverload',
    'swelledlymphnodes',
    'swollenlegs',
    'swollenbloodvessels',
    'swollenextremeties',
    'prominentveinsoncalf',
    'puffyfaceandeyes',
    'coldhandsandfeets',
    'sunkeneyes',
    'brittlenails',
    'smalldentsinnails',
    'inflammatorynails',
    'abnormalmenstruation',
    'polyuria',
    'excessivehunger',
    'increasedappetite',
    'irregularsugarlevel',
    'familyhistory',
    'historyofalcoholconsumption',
    'extramaritalcontacts',
    'receivingbloodtransfusion',
    'receivingunsterileinjections',
    'toxiclooktyphos',
    'ulcersontongue',
    'dryingandtinglinglips',
    'painbehindtheeyes',
  ],
};
